version: 2 

models:
  - name: stg_synthea_patients
    columns:
      - name: patient_id
        data_tests:
          - not_null
          - unique
      - name: birth_date
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: '1900-01-01'
                max_value:  'expression: current_date()'
        
  - name: stg_synthea_encounters
    columns:
      - name: encounter_id
        data_tests:
          - not_null
          - unique
      - name: patient_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_synthea_patients')
                field: patient_id
      - name: provider_id
        data_tests:
          - not_null
      - name: organization_id
        data_tests:
          - not_null
      - name: encounter_class_id 
        data_tests:
          - accepted_values:
              arguments:
                values: ['wellness', 'ambulatory', 'outpatient', 'inpatient', 'emergency']
      
  - name: stg_synthea_conditions
    columns:
      - name: condition_id
        data_tests:
          - not_null
          - unique 
      - name: encounter_id 
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_synthea_encounters')
                field: encounter_id
    
  - name: stg_synthea_procedures
    columns:
      - name: procedures_id
        data_tests:
          - not_null
          - unique 
      - name: encounter_id 
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_synthea_encounters')
                field: encounter_id 
